import React from 'react';
import { RotateCcw, AlertTriangle, Clock, CheckCircle2, ShieldCheck, ArrowLeft, Video, HelpCircle, Mail } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import SEOHead from '../components/SEOHead';

export default function RefundPolicyView() {
  const { navigateTo } = useStore();

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 space-y-8 text-stone-800">
      <SEOHead
        title="Refund & Cancellation Policy | Ella Creations India"
        description="Official Refund, Replacement, and Cancellation Policy for Ella Creations India. Strict consumer protection compliance under Consumer Protection (E-Commerce) Rules, 2020."
      />

      {/* Header */}
      <div className="border-b border-brand-gold/30 pb-5 space-y-2.5">
        <button
          onClick={() => navigateTo('home')}
          className="text-xs text-stone-500 hover:text-brand-rose flex items-center gap-1 font-semibold transition-colors cursor-pointer mb-1"
        >
          <ArrowLeft className="w-3.5 h-3.5" /> Back to Storefront
        </button>
        <span className="text-xs uppercase font-bold tracking-widest text-brand-gold">Consumer Protection & Returns</span>
        <h1 className="font-serif text-2xl sm:text-4xl font-bold text-stone-900">Refund & Cancellation Policy</h1>
        <p className="text-xs text-stone-500 font-mono">Effective Date: August 2026 • Governed under Consumer Protection (E-Commerce) Rules, 2020</p>
      </div>

      {/* Policy Card Body */}
      <div className="bg-white p-5 sm:p-10 rounded-3xl border border-brand-gold/20 shadow-sm space-y-8 text-xs sm:text-sm leading-relaxed">
        
        {/* Important Notice Callout */}
        <div className="bg-amber-50/90 border-l-4 border-amber-500 p-4 rounded-r-2xl space-y-1.5 text-amber-950">
          <div className="flex items-center gap-2 font-bold text-xs sm:text-sm">
            <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
            <span>Hygiene & Intimate Jewelry Standard Notice</span>
          </div>
          <p className="text-xs text-amber-900 leading-relaxed">
            Due to strict sanitary, health, and hygiene standards associated with jewelry (earrings, nose rings, chokers, and body ornaments), products once delivered and opened are strictly non-returnable and non-exchangeable for change of mind. However, <strong>every customer is 100% protected against transit damage, manufacturing defects, or wrong items delivered</strong> as outlined below.
          </p>
        </div>

        {/* Section 1: Order Cancellation Policy */}
        <section className="space-y-3">
          <h2 className="font-serif text-lg font-bold text-stone-900 flex items-center gap-2 border-b border-stone-100 pb-2">
            <Clock className="w-4 h-4 text-brand-rose" /> 1. Order Cancellation Policy
          </h2>
          <div className="space-y-2 text-stone-700">
            <p>
              We strive to dispatch orders as swiftly as possible. You may cancel an order subject to the following conditions:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                <strong>Prior to Warehouse Dispatch:</strong> You may request cancellation within <strong>4 hours of placing the order</strong> or before an Air Waybill (AWB) tracking number has been generated by contacting our customer concierge at <a href="mailto:ellacreationsindia@gmail.com" className="text-brand-rose underline font-semibold">ellacreationsindia@gmail.com</a> or via WhatsApp.
              </li>
              <li>
                <strong>Post Dispatch:</strong> Once an order is processed, packed, and handed over to our courier partner (Shiprocket, Bluedart, Delhivery, or DTDC), <strong>cancellations cannot be entertained</strong>.
              </li>
              <li>
                <strong>Cancellation by Ella Creations:</strong> We reserve the right to cancel orders under rare circumstances, such as suspected fraud, inventory inaccuracy, or undeliverable pincodes. In such cases, 100% of the prepaid amount will be refunded immediately.
              </li>
            </ul>
          </div>
        </section>

        {/* Section 2: Defect & Transit Damage Reporting */}
        <section className="space-y-3">
          <h2 className="font-serif text-lg font-bold text-stone-900 flex items-center gap-2 border-b border-stone-100 pb-2">
            <Video className="w-4 h-4 text-brand-gold" /> 2. Reporting Damaged, Defective, or Incorrect Items (48-Hour Window)
          </h2>
          <div className="space-y-2 text-stone-700">
            <p>
              Every jewelry piece undergoes multi-tier physical inspection before dispatch. If, in rare circumstances, you receive a package that arrived damaged in transit, possesses a missing gemstone, or contains an incorrect item:
            </p>
            <div className="bg-stone-50 p-4 rounded-2xl border border-stone-200 space-y-2.5">
              <span className="font-bold text-stone-900 block text-xs uppercase tracking-wider">Mandatory Verification Protocol:</span>
              <ul className="list-disc pl-5 space-y-1.5 text-xs">
                <li>
                  <strong>Statutory 48-Hour Reporting Window:</strong> You must report the issue within <strong>48 hours of physical delivery</strong> as recorded by the courier tracking log.
                </li>
                <li>
                  <strong>Unedited Continuous Unboxing Video:</strong> A 360-degree continuous, uncut video starting from showing the sealed outer tamper-evident courier bag, clear view of the shipping label, and the unboxing revealing the defect is <strong>mandatory</strong> to process defect claims and insurance settlements with courier partners.
                </li>
                <li>
                  <strong>Submission:</strong> Email the video clip, photos, and your Order ID to <a href="mailto:ellacreationsindia@gmail.com" className="text-brand-rose underline font-semibold">ellacreationsindia@gmail.com</a> or message our verified WhatsApp support.
                </li>
              </ul>
            </div>
          </div>
        </section>

        {/* Section 3: Replacement or Refund Procedure */}
        <section className="space-y-3">
          <h2 className="font-serif text-lg font-bold text-stone-900 flex items-center gap-2 border-b border-stone-100 pb-2">
            <RotateCcw className="w-4 h-4 text-brand-rose" /> 3. Replacement & Refund Resolution Process
          </h2>
          <div className="space-y-2 text-stone-700">
            <p>
              Once your claim and unboxing footage are reviewed and approved by our quality control department within 24–48 hours:
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-1">
              <div className="p-3.5 bg-brand-cream/50 rounded-2xl border border-brand-gold/20 space-y-1">
                <span className="font-bold text-stone-900 text-xs block">Priority Free Replacement (First Option)</span>
                <p className="text-xs text-stone-600">
                  A brand new replacement piece of identical specification will be dispatched via priority courier at no additional cost to you.
                </p>
              </div>
              <div className="p-3.5 bg-brand-cream/50 rounded-2xl border border-brand-gold/20 space-y-1">
                <span className="font-bold text-stone-900 text-xs block">Full Monetary Refund (If Stock Unavailable)</span>
                <p className="text-xs text-stone-600">
                  If the piece is out of production or out of stock, a 100% refund of the invoiced purchase price will be issued.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Section 4: Refund Processing Timelines */}
        <section className="space-y-3">
          <h2 className="font-serif text-lg font-bold text-stone-900 flex items-center gap-2 border-b border-stone-100 pb-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" /> 4. Refund Processing Timeframes & Modes
          </h2>
          <div className="space-y-2 text-stone-700">
            <p>
              Refunds approved by Ella Creations are initiated within <strong>24 to 48 business hours</strong> of claim validation:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                <strong>Prepaid Online Orders (Razorpay):</strong> Refunds will be credited back to the original source account (UPI, Credit/Debit Card, or Net Banking) within <strong>5 to 7 business days</strong>, subject to your issuing bank’s standard clearing cycle.
              </li>
              <li>
                <strong>Cash on Delivery (COD) Orders:</strong> Refunds will be transferred via secure direct NEFT/IMPS bank transfer or UPI. Our team will request your verified bank account details (Account Name, Account Number, and IFSC code) from your registered email address.
              </li>
              <li>
                <strong>Store Credit Option:</strong> Customers may alternatively opt for instant store credit with a 10% bonus voucher valid for 12 months.
              </li>
            </ul>
          </div>
        </section>

        {/* Section 5: Ineligible Cases */}
        <section className="space-y-3">
          <h2 className="font-serif text-lg font-bold text-stone-900 flex items-center gap-2 border-b border-stone-100 pb-2">
            <ShieldCheck className="w-4 h-4 text-stone-600" /> 5. Conditions Where Refunds/Replacements Are Not Applicable
          </h2>
          <ul className="list-disc pl-5 space-y-1.5 text-stone-700">
            <li>Defect or damage reported after the 48-hour delivery window.</li>
            <li>Damages caused due to improper handling, contact with perfume, hairspray, moisture, chlorine water, or physical breakage after receipt.</li>
            <li>Natural minor handcrafted variations inherent to traditional Kundan, Meenakari, and artisan jewelry (as described in product descriptions).</li>
            <li>Failure to provide the mandatory continuous unboxing video recording.</li>
            <li>Customized bridal sets or personalized jewelry crafted to customer specifications.</li>
          </ul>
        </section>

      </div>

      {/* Customer Grievance Callout */}
      <div className="bg-stone-950 text-white p-6 rounded-3xl border border-stone-800 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="space-y-1">
          <h3 className="font-serif text-base font-bold text-white">Need Assistance With a Return or Refund?</h3>
          <p className="text-xs text-stone-400">Our customer care team responds to all refund inquiries within 24 hours.</p>
        </div>
        <a
          href="mailto:ellacreationsindia@gmail.com"
          className="bg-brand-rose hover:bg-brand-rose/90 text-white text-xs font-semibold px-5 py-2.5 rounded-xl transition-colors cursor-pointer shrink-0 inline-flex items-center gap-1.5"
        >
          <Mail className="w-4 h-4" /> Email Support Concierge
        </a>
      </div>
    </div>
  );
}
